BREAKS = [
    "ALTER TABLE orders RENAME COLUMN cust_id TO customer_id;",
    "ALTER TABLE orders ADD COLUMN email TEXT;",
    "ALTER TABLE orders DROP COLUMN price;",
    "ALTER TABLE orders RENAME TO orders_v2;",
    "ALTER TABLE orders ALTER COLUMN price TYPE TEXT;",
    "ALTER TABLE orders ADD COLUMN phone TEXT;",
    "ALTER TABLE orders ADD COLUMN age INT NOT NULL;",
    "ALTER TABLE orders RENAME COLUMN price TO amount;",
    "ALTER TABLE orders RENAME COLUMN id TO order_id;",
    "ALTER TABLE orders DROP COLUMN cust_id;",
    "ALTER TABLE orders ALTER COLUMN cust_id TYPE TEXT;",
    "ALTER TABLE orders ALTER COLUMN price TYPE NUMERIC;",
    "ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;",
    "ALTER TABLE orders ADD COLUMN status TEXT;",
    "ALTER TABLE orders ADD COLUMN created_at TIMESTAMP;",
    "ALTER TABLE orders RENAME COLUMN cust_id TO custId;",
    "ALTER TABLE orders ADD COLUMN address TEXT;",
    "ALTER TABLE orders DROP COLUMN id;",
    "ALTER TABLE orders ADD COLUMN total FLOAT;",
    "ALTER TABLE orders ALTER COLUMN price TYPE INT;",
    "ALTER TABLE orders ADD COLUMN discount FLOAT;",
    "ALTER TABLE orders RENAME COLUMN price TO cost;",
    "ALTER TABLE orders ADD COLUMN city TEXT;",
    "ALTER TABLE orders ADD COLUMN pincode INT;",
    "ALTER TABLE orders DROP COLUMN city;",
    "ALTER TABLE orders ADD COLUMN email TEXT; ALTER TABLE orders DROP COLUMN price;",
    "ALTER TABLE orders RENAME COLUMN cust_id TO client_id;",
    "ALTER TABLE orders ADD COLUMN note TEXT;",
    "ALTER TABLE orders ALTER COLUMN cust_id TYPE BIGINT;",
    "ALTER TABLE orders ADD COLUMN extra TEXT;",
]

if __name__ == "__main__":
    print(f"total: {len(BREAKS)}")